define("ocb/resource", ["ocb/cashpang"], function(){
    var resource = {
        imagePath : "images/",
        images : {
            // "playBg"            : "bg_02.png",
            "headerBg"          : "bg_01.png",
            "playBg"            : "bg_03.png",
            "flashBg"           : "bg_04.png",
            "endBg"             : "bg_05.jpg",
            "Go"                : "msg_go.png",
            "gameOver"          : "msg_gameover.png",
            "lastpang"          : "msg_lastpang.png",
            "ready"             : "msg_ready.png",
            "noPossibleMatch"   : "msg_relocation.png",
            "Timer"             : "timeline_bar.png",
            "timelineNo"        : "timeline_no_backup.png",
            "white"             : "coin_basic_a1.png",
            "yellow"            : "coin_basic_a2.png",
            "orange"            : "coin_basic_b.png",
            "purple"            : "coin_basic_c.png",
            "blue"              : "coin_basic_g.png",
            "green"             : "coin_basic_h.png",
            "red"               : "coin_basic_s.png",
            "selected"          : "coin_select.png",
            "hint"              : "hint.png",
            "zero"              : "score_no_0.png",
            "one"               : "score_no_1.png",
            "two"               : "score_no_2.png",
            "three"             : "score_no_3.png",
            "four"              : "score_no_4.png",
            "five"              : "score_no_5.png",
            "six"               : "score_no_6.png",
            "seven"             : "score_no_7.png",
            "eight"             : "score_no_8.png",
            "nine"              : "score_no_9.png",
            "bomb"              : "ani_coin_special_01.png",
            "cross"             : "ani_coin_special_02.png",
            "pang"              : "ani_pang.png",
            // "combo"             : "combo.png",
            "c0"                : "combo_no_0.png",
            "c1"                : "combo_no_1.png",
            "c2"                : "combo_no_2.png",
            "c3"                : "combo_no_3.png",
            "c4"                : "combo_no_4.png",
            "c5"                : "combo_no_5.png",
            "c6"                : "combo_no_6.png",
            "c7"                : "combo_no_7.png",
            "c8"                : "combo_no_8.png",
            "c9"                : "combo_no_9.png",
            "comboBox"          : "combobox.png"
        },
        spriteInfo : {
            "t0" : {
                image : "timelineNo",
                x:0,
                y:0,
                width: 36,
                height: 42,
                frames: 10,
                loop: true,
                order: [0],
                duration: 400
            },
            "t1" : {
                image : "timelineNo",
                x:0,
                y:0,
                width: 36,
                height: 42,
                frames: 10,
                loop: true,
                order: [1],
                duration: 400
            },
            "t2" : {
                image : "timelineNo",
                x:0,
                y:0,
                width: 36,
                height: 42,
                frames: 10,
                loop: true,
                order: [2],
                duration: 400
            },
            "t3" : {
                image : "timelineNo",
                x:0,
                y:0,
                width: 36,
                height: 42,
                frames: 10,
                loop: true,
                order: [3],
                duration: 400
            },
            "t4" : {
                image : "timelineNo",
                x:0,
                y:0,
                width: 36,
                height: 42,
                frames: 10,
                loop: true,
                order: [4],
                duration: 400
            },
            "t5" : {
                image : "timelineNo",
                x:0,
                y:0,
                width: 36,
                height: 42,
                frames: 10,
                loop: true,
                order: [5],
                duration: 400
            },
            "t6" : {
                image : "timelineNo",
                x:0,
                y:0,
                width: 36,
                height: 42,
                frames: 10,
                loop: true,
                order: [6],
                duration: 400
            },
            "t7" : {
                image : "timelineNo",
                x:0,
                y:0,
                width: 36,
                height: 42,
                frames: 10,
                loop: true,
                order: [7],
                duration: 400
            },
            "t8" : {
                image : "timelineNo",
                x:0,
                y:0,
                width: 36,
                height: 42,
                frames: 10,
                loop: true,
                order: [8],
                duration: 400
            },
            "t9" : {
                image : "timelineNo",
                x:0,
                y:0,
                width: 36,
                height: 42,
                frames: 10,
                loop: true,
                order: [9],
                duration: 400
            },
            "bomb" : {
                image : "bomb",
                x:0,
                y:0,
                width : 135,
                height : 135,
                frames : 6,
                loop : true,
                duration : 1000,
                order : [0,1,2,3,4,5],
                easing : "linear"
            },
            "cross" : {
                image : "cross",
                x:0,
                y:0,
                width : 135,
                height : 135,
                frames : 5,
                loop : true,
                duration : 1000,
                order : [0,1,2,3,4],
                easing : "linear"
            },
            "pang" : {
                image : "pang",
                x:0,
                y:0,
                width : 180,
                height : 180,
                frames : 5,
                loop : true,
                duration : 150, //cashpang.animationDuration,
                order : [0,1,2,3,4],
                easing : "linear"
            },
            "hint" : {
                image : "hint",
                x:0,
                y:0,
                width: 135,
                height: 135,
                frames: 2,
                loop: true,
                order: [0,1],
                duration: 400
            }
        }
    };

    return resource;
});